#!/usr/bin/env bash
[[ " help deploy-webhook:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in

  help | deploy-webhook:help)
    help_content_func() {
      #shellcheck disable=SC2034
      declare desc="return deploy-webhook plugin help content"
      cat<<help_content
    deploy-webhook:help, Display deploy-webhook help
help_content
    }

    if [[ $1 = "deploy-webhook:help" ]]; then
      echo -e 'Usage: dokku deploy-webhook[:COMMAND]'
      echo ''
      echo 'Automatically call a remote URL after a container deployemnt.'
      echo ''
      echo 'Additional commands:'
      help_content_func | sort | column -c2 -t -s,
    elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
      help_content_func
    else
      cat<<help_desc
    deploy-webhook, Plugin for calling a remote URL after a container deployment
help_desc
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac

