#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/docker-options/functions"

invoke_deploy_webhook() {
  declare desc="invoke_deploy_webhook"
  local APP="$1"
  local IP="$2"
  local PORT="$3"

  local WEBHOOK_URL=$(config_get "$APP" DOKKU_DEPLOY_WEBHOOK)

  if [[ "" != "$WEBHOOK_URL" ]] ; then
      # replace the fields
      local url=${WEBHOOK_URL//\$\{IP_ADDRESS\}/${IP}}:
      url=${url//\$\{APP\}/${APP}}
      url=${url//\$\{PORT\}/${PORT}}
      
      local METHOD=$(config_get "$APP" DOKKU_DEPLOY_WEBHOOK_METHOD || "GET")
      dokku_log_info1 "Invoking webhook url $WEBHOOK_URL"
      if [[ "POST" == "$METHOD" ]] ; then
          dokku_log_info1 $(curl -q -m 5 "$url" -X "POST" -H "Content-Type: application/x-www-form-urlencoded" -d "APP=$APP" -d "IP=$IP" -d "PORT=$PORT")
      else
          dokku_log_info1 $(curl -q -m 5 "$url")
      fi
  fi
}

