[plugin]
description = "Invokes a remote URL immediately after each successful container deployment"
version = "0.1.6"
website_url = "https://github.com/IdeaSynthesis/dokku-deploy-webhook"
[plugin.config]